from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass

from ..errors import SpecificationError
from ..factorvars import FactorVariableExpression
from .specs import FixedEffect, Interaction


@dataclass(frozen=True, slots=True)
class _AbsorbTerm:
    factors: tuple[str, ...]
    slope: str | None
    order: int

    @property
    def factor_set(self) -> frozenset[str]:
        return frozenset(self.factors)


def _dedupe_ordered(values):
    return tuple(dict.fromkeys(values))


def _group_object(parts: tuple[str, ...]):
    if len(parts) == 1:
        return parts[0]
    return Interaction(*parts)


def _group_name(parts: tuple[str, ...]) -> str:
    return "#".join(parts)


def _err(message: str, expr: FactorVariableExpression, *, code: str, details=None, suggestion=None):
    return SpecificationError(
        message,
        code=code,
        stage="absorb",
        details={"expression": expr.expression, **(details or {})},
        suggestion=suggestion,
    )


def compile_absorb_factor_variable(expr: FactorVariableExpression) -> tuple[FixedEffect, ...]:
    """Compile an ``fv()`` expression into an exact absorbed-FE representation.

    The factor-variable parser is shared with explicit regressor design, but
    absorption has a different target representation.  Categorical terms
    become FE partitions and factor-by-continuous terms become heterogeneous
    slopes.  Redundant lower-order terms generated by ``##`` are eliminated
    symbolically before any observation-level FE encoding.

    Examples
    --------
    ``i(firm)`` -> ``FixedEffect('firm')``
    ``i(firm)#i(year)`` -> one joint ``firm#year`` FE
    ``i(firm)#c(t)`` -> firm-specific slope, no firm intercept
    ``i(firm)##c(t)`` -> firm intercept + firm-specific slope

    Pure continuous absorb terms and interactions containing more than one
    continuous atom are intentionally rejected because the current HDFE slope
    primitive represents one continuous slope variable at a time.
    """
    if not isinstance(expr, FactorVariableExpression):
        raise TypeError("compile_absorb_factor_variable() expects fv(...) output")

    intercept_terms: list[_AbsorbTerm] = []
    slope_terms: list[_AbsorbTerm] = []
    pure_continuous: list[tuple[str, int]] = []

    for order, term in enumerate(expr.terms):
        factors = []
        continuous = []
        for atom in term.atoms:
            if atom.kind == "factor":
                # Base levels are a parameterization choice for explicit dummy
                # columns, not for an absorbed FE column space.  Non-default
                # selectors are therefore rejected instead of silently ignored.
                if atom.base_mode != "first" or atom.base_value is not None:
                    raise _err(
                        "factor base selectors are not meaningful inside absorb=",
                        expr,
                        code="absorb.factorvars.base_selector",
                        details={"variable": atom.variable, "base_mode": atom.base_mode, "base_value": atom.base_value},
                        suggestion="Remove base=... inside absorb=. Base levels matter for explicit fv() regressors, not absorbed FE spaces.",
                    )
                factors.append(atom.variable)
            elif atom.kind == "continuous":
                continuous.append(atom.variable)
            else:  # pragma: no cover - parser contract
                raise _err(
                    f"unsupported factor-variable atom kind {atom.kind!r}", expr,
                    code="absorb.factorvars.unsupported_atom",
                )

        factors_t = _dedupe_ordered(factors)
        if len(continuous) > 1:
            raise _err(
                "absorbed factor-variable terms currently support at most one continuous atom per interaction",
                expr,
                code="absorb.factorvars.continuous_product",
                details={"continuous": tuple(continuous), "factors": factors_t},
                suggestion="Materialize the continuous product explicitly, or use one heterogeneous slope variable per interaction.",
            )
        if not factors_t:
            if continuous:
                pure_continuous.append((continuous[0], order))
                continue
            raise _err("empty absorbed factor-variable term", expr, code="absorb.factorvars.empty_term")
        if continuous:
            slope_terms.append(_AbsorbTerm(factors_t, continuous[0], order))
        else:
            intercept_terms.append(_AbsorbTerm(factors_t, None, order))

    slope_vars = {t.slope for t in slope_terms}
    unsupported_pure = [v for v, _ in pure_continuous if v not in slope_vars]
    if unsupported_pure:
        raise _err(
            "pure continuous terms cannot be absorbed without a categorical grouping factor",
            expr,
            code="absorb.factorvars.pure_continuous",
            details={"variables": tuple(dict.fromkeys(unsupported_pure))},
            suggestion="Put global continuous controls in x=/exog=. Use i(group)#c(x) or i(group)##c(x) for heterogeneous slopes.",
        )
    # A pure c(x) term generated by a full factorial is already in the span of
    # any complete set of group-specific x slopes, because sum_g 1[g]x = x.

    def maximal(terms: list[_AbsorbTerm], *, by_slope: bool) -> list[_AbsorbTerm]:
        out = []
        for i, term in enumerate(terms):
            fs = term.factor_set
            dominated = False
            for j, other in enumerate(terms):
                if i == j:
                    continue
                if by_slope and term.slope != other.slope:
                    continue
                ofs = other.factor_set
                if fs < ofs:  # strict categorical refinement by specification
                    dominated = True
                    break
                if fs == ofs and other.order < term.order:
                    dominated = True
                    break
            if not dominated:
                out.append(term)
        return out

    intercept_max = maximal(intercept_terms, by_slope=False)
    slope_max = maximal(slope_terms, by_slope=True)

    # Merge slopes that share one categorical partition.  Only an intercept
    # requested on that exact partition is merged into the same FixedEffect;
    # a distinct finer/coarser intercept remains a separate (possibly later
    # canonicalized) FE because the original expression did not request the
    # missing joint intercept.
    group_parts: dict[frozenset[str], tuple[str, ...]] = {}
    group_order: dict[frozenset[str], int] = {}
    intercept_keys: set[frozenset[str]] = set()
    slopes_by_group: dict[frozenset[str], list[tuple[int, str]]] = defaultdict(list)

    for term in intercept_max:
        key = term.factor_set
        group_parts.setdefault(key, term.factors)
        group_order[key] = min(group_order.get(key, term.order), term.order)
        intercept_keys.add(key)
    for term in slope_max:
        key = term.factor_set
        group_parts.setdefault(key, term.factors)
        group_order[key] = min(group_order.get(key, term.order), term.order)
        slopes_by_group[key].append((term.order, str(term.slope)))

    specs: list[tuple[int, FixedEffect]] = []
    all_keys = set(intercept_keys) | set(slopes_by_group)
    for key in all_keys:
        parts = group_parts[key]
        slope_pairs = sorted(slopes_by_group.get(key, ()), key=lambda item: item[0])
        slopes = tuple(dict.fromkeys(v for _, v in slope_pairs))
        has_intercept = key in intercept_keys
        name = _group_name(parts)
        specs.append((
            group_order[key],
            FixedEffect(_group_object(parts), slopes=slopes, intercept=has_intercept, name=name),
        ))

    specs.sort(key=lambda item: item[0])
    return tuple(spec for _, spec in specs)
